name: 🐛 Алдаа мэдээлэх
description: Дархай (Darhai) дээр гарсан алдаа буюу гэнэтийн зан төлөвийг мэдээлэх
title: '[Алдаа]: '
labels: ['bug']
body:
  - type: dropdown
    id: platform
    attributes:
      label: Платформ
      description: Та ямар платформ дээр ажиллаж байна вэ?
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Windows
        - Linux
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Дархайн хувилбар
      description: Та Дархайн аль хувилбарыг ашиглаж байна вэ?
      placeholder: 'жишээ нь: 1.2.2'
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Алдааны тодорхойлолт
      description: Ямар алдаа гарсныг товч бөгөөд тодорхой бичнэ үү.
      placeholder: Юу болсныг тайлбарлана уу...
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Алдааг давтах алхмууд
      description: Алдааг дахин гаргах алхмууд
      placeholder: |
        1. '...' хэсэг рүү орно
        2. '...' дээр дарна
        3. Алдаа гарна
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Хүлээгдэж байсан үр дүн
      description: Юу болох ёстой байсан бэ?
      placeholder: Юу болох ёстой байсан бэ?
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Бодит үр дүн
      description: Бодитоор юу болсон бэ?
      placeholder: Бодитоор юу болсон бэ?
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Нэмэлт мэдээлэл
      description: Асуудалтай холбоотой бусад мэдээллийг эндээ нэмнэ үү.
      placeholder: Дэлгэцийн зураг, алдааны лог гэх мэт.
